# Generated by Django 5.2.7 on 2025-11-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(max_length=10)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('account_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('INVESTMENT', 'Investment')], default='DEBIT', max_length=10)),
            ],
        ),
    ]
