# Generated by Django 5.2.7 on 2025-11-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='transactions',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
