# Generated by Django 5.2.7 on 2025-11-11 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('send_from', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_from', to='accounts.account')),
                ('send_to', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_to', to='accounts.account')),
            ],
        ),
    ]
