# Generated by Django 5.2.7 on 2025-11-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_user'),
        ('transactions', '0003_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='send_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromAccount', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='send_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toAccount', to='accounts.account'),
        ),
    ]
