# Generated by Django 5.2.7 on 2025-11-11 18:48

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0004_customuser_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accounts',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, validators=[users.validators.validate_user_age]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='99999999999', max_length=128, null=True, region=None),
        ),
    ]
